services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@7933
    # remove MYSQL_USER and MYSQL_PASSWORD for root
    ports:
    - "3307:3306"   # use 3307 on host to avoid conflict
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pRoot@7933"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  config-server:
    build: ./ConfigServerApplication_
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka:
    build: ./DiscoveryServerApplication_
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka
      - config-server
    networks:
      - microservices-net
    deploy:
      resources:
        limits:
          memory: 256M

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8090:8090"
    depends_on:
      - eureka
      - config-server
    networks:
      - microservices-net

  book-service:
    build: ./SpringBootMicroservice
    container_name: book-service
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
      eureka:
        condition: service_started
      mysql:
        condition: service_healthy
    networks:
      - microservices-net
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      config-server:
        condition: service_healthy
      eureka:
        condition: service_started
      mysql:
        condition: service_healthy
    networks:
      - microservices-net
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888

networks:
  microservices-net:
    driver: bridge